export const interests = [
  "Machine Learning",
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Artificial Intelligence",
  "Cybersecurity",
  "Cloud Computing",
  "Blockchain",
  "IoT",
  "Robotics",
];

export const majors = [
  "Biology",
  "Chemistry",
  "Computer Science",
  "Economics",
  "English",
  "History",
  "International Relations",
  "Mathematics",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Sociology and Anthropology",
  "Interdisciplinary Majors",
  "Computer Science and Entrepreneurial Leadership",
  "Mathematics and Computer Science",
  "English and Creative Writing",
  "Economics and Finance",
  "Economics and History",
  "English and Media Studies",
  "English and Performing Arts",
  "History and International Relations",
  "Politics, Philosophy, and Economics",
];

export const minors = [
  "Biology",
  "Chemistry",
  "Computer Science",
  "Creative Writing",
  "Economics",
  "Entrepreneurship",
  "Environmental Science",
  "History",
  "International Relations",
  "Mathematics",
  "Media Studies",
  "Performing Arts",
  "Philosophy",
  "Astronomy",
  "Physics",
  "Political Science",
  "Sociology and Anthropology",
  "Visual Arts",
];
